[target.thumbv7em-none-eabihf]
runner = "jlink-flasher"

rustflags = [
    # LLD (shipped with the Rust toolchain) is used as the default linker
    "-C", "link-arg=-Tlink.x",
    #    "-C", "linker=cortex-m-rt-ld",
    #    "-Z", "linker-flavor=ld",
    #    "-Z", "thinlto=no",
]


[build]
target = "thumbv7em-none-eabihf"